name: Testes com Pytest
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar bibliotecas
        run: pip install pytest pytest-cov jinja2

      - name: Executar Pytest e gerar XML
        run: pytest --cov --junitxml=resultado_testes.xml

      - name: Gerar Relatorio de Aceite HTML
        run: python gera_relatorio.py

      - name: Upload Artefato de Aceite
        uses: actions/upload-artifact@v4
        with:
          name: Termo-de-Aceite-Final
          path: termo_de_aceite.html

      - name: Enviar E-mail de Aceite
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.email }}
          password: ${{ secrets.senhaemail }}
          subject: "Vitor Samuel Goncalves Teixeira - Termo de Aceite Tecnico - Express CEP"
          to: ${{ vars.destinatario}}
          from: "Automacao GitHub Actions"
          body: "Prezado, segue em anexo o relatório de testes para validação e aceite da release."
          attachments: termo_de_aceite.html